### PR TITLE
fix UNDEFINED error because of MS response header X-DeviceConnectionStatus value changed from Connected to connected

### PR DESCRIPTION
**Pull request by nikit-cpp**
I received UNDEFINED error in my app server log
`15:58:29,627 ERROR [org.jboss.aerogear.windows.mpns.internal.Utilities] (default-threads - 44) Unmatched error code - Notification status: Received, Connection status: connected, Subscription status: Active, Status code: 200`
`15:58:29,628 ERROR [our.businness.winphone.WinPhonePush] (default-threads - 44) message fail with responce UNDEFINED`

I fix it with String#equalsIgnoreCase()

### CODE REVIEW

**Comment by mykapp** [comment]
Hi, 
nikit-cpp has fixed this problem on January 29. I am surprised this is not yet included in the main branch.
I also need this fix. Is it planned to be included in a release soon?
Regards,
Mickaël
Mickaël

**Comment by matzew** [comment]
looks good to me!

@edewit wanna merge it ?

**Comment by edewit** [comment]
@nikit-cpp super thanks for this

**Comment by mykapp** [comment]
@edewit Great, thanks you. Any idea when a new version (0.3.0 i think) will be available with this?

**Comment by matzew** [comment]
we can run something soon-ish - ok ?

On Thu, Mar 3, 2016 at 9:15 AM, Mickaël D. <notifications@github.com> wrote:

> @edewit <https://github.com/edewit> Great, thanks you. Any idea when a
> new version (0.3.0 i think) will be available with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/java-mpns/pull/11#issuecomment-191647656>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
@nikit-cpp @mykapp @edewit the release is on its vote, and early next week I guess 0.3.0 will hit maven central!

http://lists.jboss.org/pipermail/aerogear-dev/2016-March/012278.html

**Comment by nikit-cpp** [comment]
thx, guys

**Comment by mykapp** [comment]
Thx.

**Pull request merged**
